version: '3.7'
services:
    postgres-db:
        container_name: postgres-0
        image: postgres:12.3-alpine
        ports:
            - target: 5432
              published: 5432
        volumes:
            - /Users/gians/Desktop/Developer/DockerStuff/volumes/postgres:/var/lib/postgresql/data:rw

    mongo-db:
        container_name: mongo-0
        image: mongo:4.2.3-bionic
        command: [--auth]
        ports:
            - target: 27017
              published: 27017
        volumes:
            - /Users/gians/Desktop/Developer/DockerStuff/volumes/mongo:/data/db:rw

    springboot-demo:
        container_name: springboot-demo-0
        depends_on:
            - postgres-db
            - mongo-db
        image: springboot-demo:latest
        #environment:
            #  POSTGRES_USER=${POSTGRES_USER}
            #  POSTGRES_PASS=${POSTGRES_PASS}
            #  MONGO_USER=${MONGO_USER}
            #  MONGO_PASS=${MONGO_PASS}
        env_file:
            - env/staging.env
        ports:
            - target: 8080
              published: 8080
