services:
  springboot-demo:
    networks:
      - my-network
    container_name: springboot-demo-1
    image: gianlucamori/springboot-demo:latest
    pull_policy: never
    build:
      dockerfile: ./Dockerfile
    command: java -jar /release/app/springboot-demo.jar
    env_file: docker.env
    ports:
      - target: 8080
        published: 8080

networks:
  my-network:
    name: my-network
    external: true
