version: '3.9'
services:
    springboot-demo:
        container_name: springboot-demo-0
        image: gianlucamori/springboot-demo:latest
        build:
            dockerfile: ./Dockerfile
        command: java -jar /release/app/springboot-demo.jar
        environment:
            - ACTIVE_PROFILE=dev
            - POSTGRES_USER=docker
            - POSTGRES_PASS=12345
        ports:
            - target: 8080
              published: 8080
