version: '3.7'
services:
    springboot-demo:
        container_name: springboot-demo-0
        depends_on:
            - postgres-db
            - mongo-db
        image: springboot-demo:latest
        #environment:
            #  POSTGRES_USER=${POSTGRES_USER}
            #  POSTGRES_PASS=${POSTGRES_PASS}
            #  MONGO_USER=${MONGO_USER}
            #  MONGO_PASS=${MONGO_PASS}
        ports:
            - target: 8080
              published: 8080
