CREATE TABLE author (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    author_timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE book_author (
    book_id BIGINT NOT NULL REFERENCES book (id) ON UPDATE CASCADE ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES author (id) ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT book_author_pkey PRIMARY KEY (book_id, author_id)
);

