server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: native

spring:
  application:
    name: ${APP_NAME}
  mongodb:
      uri: ${MONGO_CONNECTION_STRING}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres-db-1?sslmode=${POSTGRES_SSL_MODE:disable}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    show-sql : false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgresql
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: info, health
      base-path: /

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

application:
  clients:
    quoteBaseUrl: "https://zenquotes.io/api/random"



