server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: native

spring:
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/spring-boot-demo
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/spring-boot-demo
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    show-sql : false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      mode: always
      platform: postgresql

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      exposure:
        include: info, health
      base-path: "/"
info:
  app:
    name: "@project.name@"
    version: "@project.version@"

application:
  clients:
    quoteBaseUrl: "https://zenquotes.io/api/random"



