server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: native

spring:
  application:
    name: ${APP_NAME}
  mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/mongo-db-1?authSource=admin
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgress-db-1
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    show-sql : false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgresql

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      exposure:
        include: info, health
      base-path: "/"
info:
  app:
    name: "@project.name@"
    version: "@project.version@"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

application:
  clients:
    quoteBaseUrl: "https://zenquotes.io/api/random"



