CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS person (
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(64) NOT NULL,
    book_timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS review (
    id BIGSERIAL PRIMARY KEY,
    text VARCHAR(512) NOT NULL,
    review_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    book_id BIGINT NOT NULL,

    FOREIGN KEY (book_id) REFERENCES book (id)
);

CREATE TABLE IF NOT EXISTS book_detail (
    id BIGINT PRIMARY KEY,
    pages INTEGER NOT NULL,
    isbn VARCHAR(64),
    book_detail_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

    FOREIGN KEY (id) REFERENCES book (id)
);

CREATE TABLE IF NOT EXISTS author (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    author_timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS book_author (
    book_id BIGINT NOT NULL REFERENCES book (id) ON UPDATE CASCADE ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES author (id) ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT book_author_pkey PRIMARY KEY (book_id, author_id)
);

CREATE TABLE IF NOT EXISTS student (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    insert_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    update_timestamp TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS course (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    insert_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    update_timestamp TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS student_course (
    student_id BIGINT NOT NULL REFERENCES student (id) ON UPDATE CASCADE ON DELETE CASCADE,
    course_id BIGINT NOT NULL REFERENCES course (id) ON UPDATE CASCADE ON DELETE CASCADE,
    rating BIGINT,
    insert_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    update_timestamp TIMESTAMP WITH TIME ZONE,

    CONSTRAINT student_course_pkey PRIMARY KEY (student_id, course_id)
);