name: Reusable Dispatch

env:
  MANIFEST_REPO: giansluca/multi-k8s

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      app_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Manifest Update
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.MANIFEST_REPO }}/dispatches \
            --data '{
              "event_type": "update-image",
              "client_payload": {
                "env": "env": "${{ inputs.env }}",
                "app_name": "${{ inputs.app_name }}",
                "image_name": "${{ inputs.image_name }}",
                "tag": "${{ inputs.tag }}",
              }
            }'
          
