name: Build and Push Docker Image

env:
  REGISTRY_NAME: gianlucamori
  APP_NAME: springboot-demo
  IMAGE_NAME: gianlucamori/springboot-demo
  MANIFEST_REPO: giansluca/multi-k8s
on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]

jobs:
  # --- JOB 1: DEVELOPMENT (Commits on Master) ---
  job_dev:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    environment: dev  # GitHub environment 'dev' must exist in repo settings
    outputs:
      sha: ${{ steps.vars.outputs.sha }} # Map step output to job output
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push Dev Image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: |
#            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha }}
#            ${{ env.IMAGE_NAME }}:latest

  deploy_dev:
    needs: job_dev
    uses: ./.github/workflows/_reusable-dispatch.yml
    with:
      env: "dev",
      app_name: ${{ env.APP_NAME }},
      image_name: ${{ env.IMAGE_NAME }},
      tag: ${{ needs.job_dev.outputs.sha }}
    secrets:
      token: ${{ secrets.MANIFEST_REPO_TOKEN }}

  # --- JOB 2: TESTING (Git Tags) ---
  job_test:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment: test  # GitHub environment 'test' must exist in repo settings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push Test Image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  deploy_test:
    needs: job_test
    uses: ./.github/workflows/_reusable-dispatch.yml
    with:
      env: "test",
      app_name: ${{ env.APP_NAME }},
      image_name: ${{ env.IMAGE_NAME }},
      tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.MANIFEST_REPO_TOKEN }}